version: '3.9'

services:
  db:
    image: postgres
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  api:
    depends_on:
      - db
    build:
      dockerfile: apps/api/Dockerfile
      context: ../.
    restart: unless-stopped
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    environment:
      - NODE_ENV=production
      - DB_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}

  web:
    build:
      dockerfile: apps/web/Dockerfile
      context: ../.
    restart: unless-stopped
    ports:
      - 4200:4200
